// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class AuditLog
{
    public long AuditId { get; set; }

    public string TableName { get; set; } = string.Empty;

    public string KeyValues { get; set; } = string.Empty;

    public string OldValues { get; set; } = string.Empty;

    public string NewValues { get; set; } = string.Empty;

    public string Action { get; set; } = string.Empty;

    public string? PerformedByUserId { get; set; }

    public DateTime PerformedAt { get; set; }

    public virtual User PerformedByUser { get; set; } = default!;
}