// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class BatteryHealthLog
{
    public long BatteryHealthLogId { get; set; }

    public int BatteryId { get; set; }

    public DateTime RecordedAt { get; set; }

    public decimal? SoH { get; set; }

    public int? CycleCount { get; set; }

    public decimal? Temperature { get; set; }

    public string Notes { get; set; } = string.Empty;

    public virtual Battery Battery { get; set; } = default!;
}