// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class BatteryModel
{
    public int BatteryModelId { get; set; }

    public string ModelCode { get; set; } = string.Empty;

    public string Manufacturer { get; set; } = string.Empty;

    public decimal CapacityKwh { get; set; }

    public string Chemistry { get; set; } = string.Empty;

    public string CompatibleVehicleTypes { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Battery> Batteries { get; set; } = new List<Battery>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}