// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Battery
{
    public int BatteryId { get; set; }

    public string SerialNumber { get; set; } = string.Empty;

    public int BatteryModelId { get; set; }

    public decimal? CurrentSoH { get; set; }

    public int? CycleCount { get; set; }

    public string Status { get; set; } = string.Empty;

    public DateTime? LastMaintenance { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<BatteryHealthLog> BatteryHealthLogs { get; set; } = new List<BatteryHealthLog>();

    public virtual BatteryModel BatteryModel { get; set; } = default!;

    public virtual ICollection<InterStationTransfer> InterStationTransfers { get; set; } = new List<InterStationTransfer>();

    public virtual ICollection<StationInventory> StationInventories { get; set; } = new List<StationInventory>();

    public virtual ICollection<SwapTransaction> SwapTransactionIncomingBatteries { get; set; } = new List<SwapTransaction>();

    public virtual ICollection<SwapTransaction> SwapTransactionOutgoingBatteries { get; set; } = new List<SwapTransaction>();
}