// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Driver
{
    public int DriverId { get; set; }

    public string UserId { get; set; }

    public string PreferredPaymentMethod { get; set; }

    public int? TotalSwaps { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual User User { get; set; }
}