// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class InterStationTransfer
{
    public long TransferId { get; set; }

    public int FromStationId { get; set; }

    public int ToStationId { get; set; }

    public int BatteryId { get; set; }

    public string? RequestedByUserId { get; set; }

    public string? ApprovedByUserId { get; set; }

    public string Status { get; set; }

    public DateTime RequestedAt { get; set; }

    public DateTime? CompletedAt { get; set; }

    public virtual User ApprovedByUser { get; set; }

    public virtual Battery Battery { get; set; }

    public virtual Station FromStation { get; set; }

    public virtual User RequestedByUser { get; set; }

    public virtual Station ToStation { get; set; }
}