// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using Domain.Enums;
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Payment
{
    public long PaymentId { get; set; }

    public long? SwapTransactionId { get; set; }

    public int? ReservationId { get; set; }

    public int? SubscriptionId { get; set; }

    public string UserId { get; set; } = string.Empty;

    public decimal Amount { get; set; }

    public string Currency { get; set; } = "VND";

    public string Method { get; set; } = "PayOS";

    public string Type { get; set; } = PaymentType.SwapFee;

    public string Status { get; set; } = PaymentStatus2.Pending;

    public string TransactionRef { get; set; } = string.Empty;

    public string? PayOSOrderCode { get; set; }

    public string? Description { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public long? ParentPaymentId { get; set; }

    public string? WebhookPayload { get; set; }

    public virtual SwapTransaction? SwapTransaction { get; set; }

    public virtual Reservation? Reservation { get; set; }

    public virtual Subscription? Subscription { get; set; }

    public virtual User User { get; set; } = default!;

    public virtual Payment? ParentPayment { get; set; }

    public virtual ICollection<Payment> ChildPayments { get; set; } = new List<Payment>();
}