// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Payment
{
    public long PaymentId { get; set; }

    public long? SwapTransactionId { get; set; }

    public string UserId { get; set; }

    public decimal Amount { get; set; }

    public string Currency { get; set; }

    public string Method { get; set; }

    public string Status { get; set; }

    public string TransactionRef { get; set; }

    public DateTime? PaidAt { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual SwapTransaction SwapTransaction { get; set; }

    public virtual User User { get; set; }
}