// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Rating
{
    public long RatingId { get; set; }

    public long? SwapTransactionId { get; set; }

    public string UserId { get; set; }

    public int? StationId { get; set; }

    public byte Score { get; set; }

    public string Comment { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Station Station { get; set; }

    public virtual SwapTransaction SwapTransaction { get; set; }

    public virtual User User { get; set; }
}