// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Reservation
{
    public int ReservationId { get; set; }

    public string UserId { get; set; }

    public int StationId { get; set; }

    public int? VehicleId { get; set; }

    public DateTime ReservedFrom { get; set; }

    public DateTime ReservedTo { get; set; }

    public string Status { get; set; }

    public int? ReservedBatteryModelId { get; set; }

    public DateTime CreatedAt { get; set; }
    public DateTime? UpdatedAt { get; set; }
    public virtual BatteryModel ReservedBatteryModel { get; set; }

    public virtual Station Station { get; set; }

    public virtual ICollection<SwapTransaction> SwapTransactions { get; set; } = new List<SwapTransaction>();

    public virtual User User { get; set; }

    public virtual Vehicle Vehicle { get; set; }
    public virtual ICollection<ReservationAllocation> ReservationAllocations { get; set; } = new List<ReservationAllocation>();
}