// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class StationInventory
{
    public int StationInventoryId { get; set; }

    public int StationId { get; set; }

    public int BatteryId { get; set; }

    public string SlotNumber { get; set; } = string.Empty;

    public string Status { get; set; } = string.Empty;

    public DateTime? CheckedAt { get; set; }

    public virtual Battery Battery { get; set; } = default!;

    public virtual Station Station { get; set; } = default!;
}