// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Station
{
    public int StationId { get; set; }

    public string Code { get; set; } = string.Empty;

    public string Name { get; set; } = string.Empty;

    public string Address { get; set; } = string.Empty;

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public int Capacity { get; set; }

    public string Phone { get; set; } = string.Empty;

    public byte Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual ICollection<InterStationTransfer> InterStationTransferFromStations { get; set; } = new List<InterStationTransfer>();

    public virtual ICollection<InterStationTransfer> InterStationTransferToStations { get; set; } = new List<InterStationTransfer>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual ICollection<StationInventory> StationInventories { get; set; } = new List<StationInventory>();

    public virtual ICollection<StationStaff> StationStaffs { get; set; } = new List<StationStaff>();

    public virtual ICollection<SupportTicket> SupportTickets { get; set; } = new List<SupportTicket>();

    public virtual ICollection<SwapTransaction> SwapTransactions { get; set; } = new List<SwapTransaction>();
}