// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class StationStaff
{
    public int StationStaffId { get; set; }

    public int StationId { get; set; }

    public string UserId { get; set; }

    public string Role { get; set; }

    public bool IsActive { get; set; }

    public virtual Station Station { get; set; }

    public virtual User User { get; set; }
}