// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class SubscriptionPackage
{
    public int PackageId { get; set; }

    public string Name { get; set; } = string.Empty;

    public string BillingCycle { get; set; } = string.Empty;

    public decimal Price { get; set; }

    public int IncludedSwaps { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();
}