// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Subscription
{
    public int SubscriptionId { get; set; }

    public string UserId { get; set; }

    public int PackageId { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Status { get; set; }

    public int? RemainingSwaps { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual SubscriptionPackage Package { get; set; }

    public virtual User User { get; set; }
}