// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class SupportTicket
{
    public long TicketId { get; set; }

    public string UserId { get; set; }

    public int? StationId { get; set; }

    public string Subject { get; set; }

    public string Description { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Station Station { get; set; }

    public virtual User User { get; set; }
}