// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class SwapTransaction
{
    public long SwapTransactionId { get; set; }

    public int? ReservationId { get; set; }

    public int StationId { get; set; }

    public string CustomerUserId { get; set; } = string.Empty;

    public string? StaffUserId { get; set; }

    public int? OutgoingBatteryId { get; set; }

    public int? IncomingBatteryId { get; set; }

    public DateTime SwapStartedAt { get; set; }

    public DateTime? SwapFinishedAt { get; set; }

    public string SwapStatus { get; set; } = string.Empty;

    public decimal Price { get; set; }

    public string Notes { get; set; } = string.Empty;

    public DateTime CreatedAt { get; set; }

    public virtual User CustomerUser { get; set; } = default!;

    public virtual Battery IncomingBattery { get; set; } = default!;

    public virtual Battery OutgoingBattery { get; set; } = default!;

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual Reservation Reservation { get; set; } = default!;

    public virtual User StaffUser { get; set; } = default!;

    public virtual Station Station { get; set; } = default!;
}