// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class User : IdentityUser
{
    public string FullName { get; set; }
    public DateTime CreatedAt { get; set; }
    public string RefreshToken { get; set; }
    public DateTime RefreshTokenExpiryTime { get; set; }

    public virtual ICollection<AuditLog> AuditLogs { get; set; } = new List<AuditLog>();

    public virtual Driver Driver { get; set; }

    public virtual ICollection<InterStationTransfer> InterStationTransferApprovedByUsers { get; set; } = new List<InterStationTransfer>();

    public virtual ICollection<InterStationTransfer> InterStationTransferRequestedByUsers { get; set; } = new List<InterStationTransfer>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Rating> Ratings { get; set; } = new List<Rating>();

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual ICollection<StationStaff> StationStaffs { get; set; } = new List<StationStaff>();

    public virtual ICollection<Subscription> Subscriptions { get; set; } = new List<Subscription>();

    public virtual ICollection<SupportTicket> SupportTickets { get; set; } = new List<SupportTicket>();

    public virtual ICollection<SwapTransaction> SwapTransactionCustomerUsers { get; set; } = new List<SwapTransaction>();

    public virtual ICollection<SwapTransaction> SwapTransactionStaffUsers { get; set; } = new List<SwapTransaction>();

    public virtual ICollection<Vehicle> Vehicles { get; set; } = new List<Vehicle>();
}