// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models;

public partial class Vehicle
{
    public int VehicleId { get; set; }

    public string UserId { get; set; }

    public string Vin { get; set; }

    public string Make { get; set; }

    public string Model { get; set; }

    public int? Year { get; set; }

    public int? BatteryModelPreferenceId { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual BatteryModel BatteryModelPreference { get; set; }

    public virtual ICollection<Reservation> Reservations { get; set; } = new List<Reservation>();

    public virtual User User { get; set; }
}